#!/bin/sh

# Usage: build has_native

set -e 
LOC=`dirname $0`

. $LOC/pkg-builder

NATIVE=$1

add lib pkg/META		
add lib src/react.mli	
add lib src/react.cmti	
add lib src/react.cmi
add lib src/react.cmx
add lib src/react.cma
add lib src/react.a
add lib src/react.cmxa
add lib src/react.cmxs

add doc README.md
add doc CHANGES.md
add doc test/breakout.ml
add doc test/clock.ml

build
install react
